scripts/desktop-launch
snap/snapcraft.yaml

fix localisation support

---

scripts/desktop-launch
snap/snapcraft.yaml

Also reorders some parts for improved dependency sharing
fixes #29 
fixes #30

update to 2.10.2

---

snap/snapcraft.yaml

Add potentially missing python setuptools
Add missing dependency definition on pango for shared-mime-info

Fix build again

---

.travis.yml

Make use of the snaps addon and the fact that xenial is now part of the public offering.
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

travis.yml: use latest features

---

snap/snapcraft.yaml

.. and lots of tidying up and refinements.

fix mypaint brushes. fix eps import.

---

.travis.yml

Use lxd to build base18 snaps in travis

Switch to --use-lxd

---

snap/snapcraft.yaml

GIMP 2.10.12

---

snap/snapcraft.yaml

Add compile-time optimisations

---

patches/desktop-launch.patch
snap/snapcraft.yaml

Remove gimp help docs because they're hooge.

Reduce snap size

---

snap/snapcraft.yaml

Incorrect number of `../` used.
This should fix the automated review errors.

Fix symlinks pointing outside snap

---

snap/snapcraft.yaml

Fix babl and gegl paths

---

snap/snapcraft.yaml

Fix python path

---

snap/hooks/refresh

remove erroneously added hook - wrong name

---

snap/snapcraft.yaml

ref: https://forum.snapcraft.io/t/refreshing-gimp-snap-failed-cannot-create-symlink-in-etc-gimp-existing-file-in-the-way/14995/9

Fix layout breakage

---

snap/snapcraft.yaml

Update to 2.10.18

---

patches/desktop-launch.patch
snap/snapcraft.yaml

Fix build & add heif support

---

scripts/build-ld-cache
scripts/check-ld-cache

Simplify ld.so.cache generation

---

snap/snapcraft.yaml

Add Evince for print preview

---

.travis.yml
snap/snapcraft.yaml

Update to gimp 2.10.20

---

desktop-launch/Makefile
desktop-launch/common/desktop-exports
desktop-launch/common/init
desktop-launch/common/mark-and-exec
desktop-launch/gnome/launcher-specific
desktop-launch/kde-neon/launcher-specific
desktop-launch/kde-neon/locale-gen
desktop-launch/src/bindtextdomain.c
snap/snapcraft.yaml

Add g'mic plugin

---

.travis.yml
snap/snapcraft.yaml

Fix path to iso-codes

---

snap/snapcraft.yaml

Gimp 2.10.22

---

snap/snapcraft.yaml

Fix for heif image support

---

snap/snapcraft.yaml

* Add more complete build and stage packages

Add some missing dependencies

---

snap/snapcraft.yaml

Fix broken build - incorrect package names

---

.github/workflows/build-prs.yml

* Add GitHub Actions workflow to test-build Pull Requests

Add build-prs.yml

---

.github/workflows/build-prs.yml
snap/local/slots-declaration.json

Add slots delcaration for review-tools test in GH Actions

---

.github/workflows/build-prs.yml
snap/snapcraft.yaml

* Disable i386 build
* Disable ppc64el build
* Disable s390x build
* Fix build on armhf by using `libheif` from apt

Build fixes

---

snap/snapcraft.yaml

Update to GIMP 2.10.28

---

snap/snapcraft.yaml

Switch to LZO Compression

---

snap/snapcraft.yaml

Bump GIMP to version 2.10.30

---

snap/snapcraft.yaml

Re-enable GTK2 Common Themes

---

snap/snapcraft.yaml

Signed-off-by: Dani Llewellyn <dani@bowlhat.net>

Bump gegl and babl

---

snap/snapcraft.yaml

Add LTO to compilations where it doesn't fail

---

snap/snapcraft.yaml

note that this is filed against the `preview` branch as it is for a separate track in the snap store (build and release is handled at https://launchpad.net/~diddledani/gimp-snap/+snap/gimp-preview via a mirror of the `preview` git branch)

Initial preview build
